coverage:
  range: 80...95
  round: up
  precision: 1
  status:
    project:
      default:
        target: auto
        informational: false
        only_pulls: true
    patch:
      default:
        target: 90%
        informational: false
        only_pulls: true
