CREATE TABLE catalogdb.bhm_efeds_veto (
    programname character varying(5),
    chunk character varying(7),
    platesn2 real,
    plate integer,
    tile integer,
    mjd integer,
    fiberid integer,
    run2d character varying(7),
    run1d character varying(7),
    plug_ra double precision,
    plug_dec double precision,
    z_err real,
    rchi2 real,
    dof integer,
    rchi2diff real,
    wavemin real,
    wavemax real,
    wcoverage real,
    zwarning integer,
    sn_median real[],
    sn_median_all real,
    spectroflux real[],
    spectroflux_ivar real[],
    anyandmask integer,
    anyormask integer,
    pk bigint NOT NULL
);
