CREATE TABLE catalogdb.bhm_rm_v0 (
    field_name character varying(8),
    ra double precision,
    "dec" double precision,
    distance double precision,
    pos_ref character varying(4),
    ebv double precision,
    des integer,
    coadd_object_id bigint,
    ra_des double precision,
    dec_des double precision,
    extended_coadd integer,
    psfmag_des double precision[],
    psfmagerr_des double precision[],
    mag_auto_des double precision[],
    magerr_auto_des double precision[],
    imaflags_iso integer[],
    separation_des double precision,
    ps1 integer,
    objid_ps1 bigint,
    ra_ps1 double precision,
    dec_ps1 double precision,
    class_ps1 double precision,
    psfmag_ps1 double precision[],
    psfmagerr_ps1 double precision[],
    kronmag_ps1 double precision[],
    kronmagerr_ps1 double precision[],
    infoflag2 integer[],
    separation_ps1 double precision,
    nsc integer,
    id_nsc bigint,
    ra_nsc double precision,
    dec_nsc double precision,
    class_star double precision,
    mag_nsc double precision[],
    magerr_nsc double precision[],
    flags_nsc integer,
    separation_nsc double precision,
    sdss integer,
    objid_sdss bigint,
    ra_sdss double precision,
    dec_sdss double precision,
    type_sdss integer,
    psfmag_sdss double precision[],
    psfmagerr_sdss double precision[],
    modelmag_sdss double precision[],
    modelmagerr_sdss double precision[],
    clean_sdss integer,
    separation_sdss double precision,
    gaia integer,
    source_id_gaia bigint,
    mg double precision,
    mag_gaia double precision[],
    magerr_gaia double precision[],
    parallax double precision,
    parallax_error double precision,
    plxsig double precision,
    pmra double precision,
    pmra_error double precision,
    pmdec double precision,
    pmdec_error double precision,
    pmsig double precision,
    unwise integer,
    objid_unwise character varying(16),
    ra_unwise double precision,
    dec_unwise double precision,
    mag_unwise double precision[],
    magerr_unwise double precision[],
    flags_unwise integer[],
    separation_unwise double precision,
    near_ir integer,
    survey_ir character varying(6),
    sourceid_ir bigint,
    ra_ir double precision,
    dec_ir double precision,
    mag_ir double precision[],
    magerr_ir double precision[],
    separation_ir double precision,
    optical_survey character varying(4),
    mi double precision,
    cal_skewt_qso integer,
    nband_optical_use integer,
    use_unwise integer,
    use_nir integer,
    photo_combination character varying(17),
    log_qso double precision,
    log_star double precision,
    log_galaxy double precision,
    p_qso double precision,
    p_star real,
    p_galaxy double precision,
    class_skewt_qso character varying(6),
    skewt_qso integer,
    p_qso_prior double precision,
    p_star_prior real,
    p_galaxy_prior double precision,
    class_skewt_qso_prior character varying(6),
    skewt_qso_prior integer,
    photoz_qso double precision,
    photoz_qso_lower double precision,
    photoz_qso_upper double precision,
    prob_photoz_qso double precision,
    photoz_galaxy double precision,
    photoz_galaxy_lower double precision,
    photoz_galaxy_upper double precision,
    pqso_xdqso double precision,
    photoz_xdqso double precision,
    prob_rf_gaia_unwise double precision,
    photoz_gaia_unwise double precision,
    des_var_nepoch integer[],
    des_var_status integer[],
    des_var_rms double precision[],
    des_var_sigrms double precision[],
    des_var_sn double precision[],
    des_var_sn_max double precision,
    ps1_var_nepoch integer[],
    ps1_var_status integer[],
    ps1_var_rms double precision[],
    ps1_var_sigrms double precision[],
    ps1_var_sn double precision[],
    ps1_var_sn_max double precision,
    spec_q integer,
    spec_strmask character varying(6),
    spec_bitmask bigint,
    specz double precision,
    specz_ref character varying(16),
    photo_q integer,
    photo_strmask character varying(3),
    photo_bitmask bigint,
    photoz double precision,
    pqso_photo double precision,
    photoz_ref character varying(16),
    pk bigint NOT NULL
);
