CREATE TABLE catalogdb.catwise (
    source_name character varying(21),
    source_id character varying(25) NOT NULL,
    ra double precision,
    "dec" double precision,
    sigra real,
    sigdec real,
    sigradec real,
    wx real,
    wy real,
    w1sky real,
    w1sigsk real,
    w1conf real,
    w2sky real,
    w2sigsk real,
    w2conf real,
    w1fitr real,
    w2fitr real,
    w1snr real,
    w2snr real,
    w1flux double precision,
    w1sigflux double precision,
    w2flux double precision,
    w2sigflux double precision,
    w1mpro real,
    w1sigmpro double precision,
    w1rchi2 double precision,
    w2mpro real,
    w2sigmpro double precision,
    w2rchi2 double precision,
    rchi2 double precision,
    nb smallint,
    na smallint,
    w1sat double precision,
    w2sat double precision,
    w1mag real,
    w1sigm real,
    w1flg integer,
    w1cov real,
    w2mag real,
    w2sigm real,
    w2flg integer,
    w2cov real,
    w1mag_1 real,
    w1sigm_1 real,
    w1flg_1 bigint,
    w2mag_1 real,
    w2sigm_1 real,
    w2flg_1 bigint,
    w1mag_2 real,
    w1sigm_2 real,
    w1flg_2 bigint,
    w2mag_2 real,
    w2sigm_2 real,
    w2flg_2 bigint,
    w1mag_3 real,
    w1sigm_3 real,
    w1flg_3 bigint,
    w2mag_3 real,
    w2sigm_3 real,
    w2flg_3 bigint,
    w1mag_4 real,
    w1sigm_4 real,
    w1flg_4 bigint,
    w2mag_4 real,
    w2sigm_4 real,
    w2flg_4 bigint,
    w1mag_5 real,
    w1sigm_5 real,
    w1flg_5 bigint,
    w2mag_5 real,
    w2sigm_5 real,
    w2flg_5 bigint,
    w1mag_6 real,
    w1sigm_6 real,
    w1flg_6 bigint,
    w2mag_6 real,
    w2sigm_6 real,
    w2flg_6 bigint,
    w1mag_7 real,
    w1sigm_7 real,
    w1flg_7 bigint,
    w2mag_7 real,
    w2sigm_7 real,
    w2flg_7 bigint,
    w1mag_8 real,
    w1sigm_8 real,
    w1flg_8 bigint,
    w2mag_8 real,
    w2sigm_8 real,
    w2flg_8 bigint,
    w1nm bigint,
    w1m integer,
    w1magp real,
    w1sigp1 real,
    w1sigp2 real,
    w1k real,
    w1ndf integer,
    w1mlq real,
    w1mjdmin double precision,
    w1mjdmax double precision,
    w1mjdmean double precision,
    w2nm bigint,
    w2m integer,
    w2magp real,
    w2sigp1 real,
    w2sigp2 real,
    w2k real,
    w2ndf integer,
    w2mlq real,
    w2mjdmin double precision,
    w2mjdmax double precision,
    w2mjdmean double precision,
    rho12 smallint,
    q12 smallint,
    niters bigint,
    nsteps bigint,
    mdetid bigint,
    p1 double precision,
    p2 double precision,
    meanobsmjd double precision,
    ra_pm double precision,
    dec_pm double precision,
    sigra_pm real,
    sigdec_pm real,
    sigradec_pm real,
    pmra real,
    pmdec real,
    sigpmra real,
    sigpmdec real,
    w1snr_pm real,
    w2snr_pm real,
    w1flux_pm double precision,
    w1sigflux_pm double precision,
    w2flux_pm double precision,
    w2sigflux_pm double precision,
    w1mpro_pm real,
    w1sigmpro_pm real,
    w1rchi2_pm double precision,
    w2mpro_pm real,
    w2sigmpro_pm real,
    w2rchi2_pm double precision,
    rchi2_pm double precision,
    pmcode character varying(5),
    niters_pm bigint,
    nsteps_pm bigint,
    dist real,
    dw1mag real,
    rch2w1 real,
    dw2mag real,
    rch2w2 real,
    elon_avg double precision,
    elonsig real,
    elat_avg double precision,
    elatsig real,
    delon real,
    delonsig real,
    delat real,
    delatsig real,
    delonsnr real,
    delatsnr real,
    chi2pmra double precision,
    chi2pmdec double precision,
    ka integer,
    k1 integer,
    k2 integer,
    km integer,
    par_pm real,
    par_pmsig real,
    par_stat real,
    par_sigma real,
    dist_x double precision,
    cc_flags character varying(16),
    w1cc_map bigint,
    w1cc_map_str character varying(20),
    w2cc_map bigint,
    w2cc_map_str character varying(20),
    n_aw integer,
    ab_flags character varying(9),
    w1ab_map bigint,
    w1ab_map_str character varying(13),
    w2ab_map bigint,
    w2ab_map_str character varying(13),
    glon double precision,
    glat double precision,
    elon double precision,
    elat double precision
);
