CREATE TABLE catalogdb.gaia_dr2_wd_sdss (
    pk integer NOT NULL,
    wd text,
    n_wd text,
    source integer,
    sdss text,
    ra double precision,
    "dec" double precision,
    umag real,
    e_umag real,
    gmag real,
    e_gmag real,
    rmag real,
    e_rmag real,
    imag real,
    e_imag real,
    zmag real,
    e_zmag real,
    plate integer,
    mjd integer,
    fiber integer,
    snr real,
    spclass text
);
