CREATE TABLE catalogdb.glimpse360 (
    designation character(26),
    tmass_designation character(16),
    tmass_cntr integer,
    l double precision,
    b double precision,
    dl double precision,
    db double precision,
    ra double precision,
    "dec" double precision,
    dra double precision,
    ddec double precision,
    csf integer,
    mag_j real,
    dj_m real,
    mag_h real,
    dh_m real,
    mag_ks real,
    dks_m real,
    mag3_6 real,
    d3_6m real,
    mag4_5 real,
    d4_5m real,
    mag5_8 real,
    d5_8m real,
    mag8_0 real,
    d8_0m real,
    f_j real,
    df_j real,
    f_h real,
    df_h real,
    f_ks real,
    df_ks real,
    f3_6 real,
    df3_6 real,
    f4_5 real,
    df4_5 real,
    f5_8 real,
    df5_8 real,
    f8_0 real,
    df8_0 real,
    rms_f3_6 real,
    rms_f4_5 real,
    rms_f5_8 real,
    rms_f8_0 real,
    sky_3_6 real,
    sky_4_5 real,
    sky_5_8 real,
    sky_8_0 real,
    sn_j real,
    sn_h real,
    sn_ks real,
    sn_3_6 real,
    sn_4_5 real,
    sn_5_8 real,
    sn_8_0 real,
    dens_3_6 real,
    dens_4_5 real,
    dens_5_8 real,
    dens_8_0 real,
    m3_6 integer,
    m4_5 integer,
    m5_8 integer,
    m8_0 integer,
    n3_6 integer,
    n4_5 integer,
    n5_8 integer,
    n8_0 integer,
    sqf_j integer,
    sqf_h integer,
    sqf_ks integer,
    sqf_3_6 integer,
    sqf_4_5 integer,
    sqf_5_8 integer,
    sqf_8_0 integer,
    mf3_6 integer,
    mf4_5 integer,
    mf5_8 integer,
    mf8_0 integer,
    pkey bigint NOT NULL
);
