CREATE TABLE catalogdb.guvcat (
    objid bigint NOT NULL,
    photoextractid bigint,
    mpstype text,
    avaspra double precision,
    avaspdec double precision,
    fexptime real,
    nexptime real,
    ra double precision,
    "dec" double precision,
    glon double precision,
    glat double precision,
    tilenum integer,
    img integer,
    subvisit integer,
    fov_radius real,
    type integer,
    band integer,
    e_bv real,
    istherespectrum smallint,
    chkobj_type smallint,
    fuv_mag real,
    fuv_magerr real,
    nuv_mag real,
    nuv_magerr real,
    fuv_mag_auto real,
    fuv_magerr_auto real,
    nuv_mag_auto real,
    nuv_magerr_auto real,
    fuv_mag_aper_4 real,
    fuv_magerr_aper_4 real,
    nuv_mag_aper_4 real,
    nuv_magerr_aper_4 real,
    fuv_mag_aper_6 real,
    fuv_magerr_aper_6 real,
    nuv_mag_aper_6 real,
    nuv_magerr_aper_6 real,
    fuv_artifact smallint,
    nuv_artifact smallint,
    fuv_flags smallint,
    nuv_flags smallint,
    fuv_flux real,
    fuv_fluxerr real,
    nuv_flux real,
    nuv_fluxerr real,
    fuv_x_image real,
    fuv_y_image real,
    nuv_x_image real,
    nuv_y_image real,
    fuv_fwhm_image real,
    nuv_fwhm_image real,
    fuv_fwhm_world real,
    nuv_fwhm_world real,
    nuv_class_star real,
    fuv_class_star real,
    nuv_ellipticity real,
    fuv_ellipticity real,
    nuv_theta_j2000 real,
    nuv_errtheta_j2000 real,
    fuv_theta_j2000 real,
    fuv_errtheta_j2000 real,
    fuv_ncat_fwhm_image real,
    fuv_ncat_flux_radius_3 real,
    nuv_kron_radius real,
    nuv_a_world real,
    nuv_b_world real,
    fuv_kron_radius real,
    fuv_a_world real,
    fuv_b_world real,
    nuv_weight real,
    fuv_weight real,
    prob real,
    sep real,
    nuv_poserr real,
    fuv_poserr real,
    ib_poserr real,
    nuv_pperr real,
    fuv_pperr real,
    corv text,
    grank smallint,
    ngrank smallint,
    primgid bigint,
    groupgid text,
    grankdist smallint,
    ngrankdist bigint,
    primgiddist bigint,
    groupgiddist text,
    groupgidtot text,
    difffuv real,
    diffnuv real,
    difffuvdist real,
    diffnuvdist real,
    sepas real,
    sepasdist real,
    inlargeobj text,
    largeobjsize real
);
