CREATE TABLE catalogdb.marvels_dr11_star (
    starname character varying NOT NULL,
    twomass_name character varying,
    plate character varying,
    gsc_name character varying,
    tyc_name character varying,
    hip_name character varying,
    ra_final double precision,
    dec_final double precision,
    gsc_b double precision,
    gsc_v double precision,
    twomass_j real,
    twomass_h real,
    twomass_k real,
    sp1 character varying,
    sp2 character varying,
    rpm_log_g character varying,
    teff real,
    log_g real,
    feh real,
    gsc_b_e real,
    gsc_v_e real,
    twomass_j_e real,
    twomass_h_e real,
    twomass_k_e real,
    teff_e real,
    log_g_e real,
    feh_e real,
    epoch_0 real,
    ra_0 double precision,
    dec_0 double precision,
    ra_twomass double precision,
    dec_twomass double precision,
    gsc_pm_ra double precision,
    gsc_pm_dec double precision,
    gsc_pm_ra_e double precision,
    gsc_pm_dec_e double precision,
    tyc_b real,
    tyc_b_e real,
    tyc_v real,
    tyc_v_e real,
    hip_plx real,
    hip_plx_e real,
    hip_sptype character varying,
    twomass_designation text,
    tycho2_designation text
);
