CREATE TABLE catalogdb.sdss_dr16_specobj (
    specobjid numeric(20,0) NOT NULL,
    bestobjid bigint,
    fluxobjid bigint,
    targetobjid bigint,
    plateid numeric(20,0),
    scienceprimary smallint,
    sdssprimary smallint,
    legacyprimary smallint,
    segueprimary smallint,
    segue1primary smallint,
    segue2primary smallint,
    bossprimary smallint,
    bossspecobjid integer,
    firstrelease character varying(32),
    survey character varying(32),
    instrument character varying(32),
    programname character varying(32),
    chunk character varying(32),
    platerun character varying(32),
    mjd integer,
    plate smallint,
    fiberid smallint,
    run1d character varying(32),
    run2d character varying(32),
    tile integer,
    designid integer,
    legacy_target1 bigint,
    legacy_target2 bigint,
    special_target1 bigint,
    special_target2 bigint,
    segue1_target1 bigint,
    segue1_target2 bigint,
    segue2_target1 bigint,
    segue2_target2 bigint,
    boss_target1 bigint,
    eboss_target0 bigint,
    eboss_target1 bigint,
    eboss_target2 bigint,
    eboss_target_id bigint,
    ancillary_target1 bigint,
    ancillary_target2 bigint,
    thing_id_targeting bigint,
    thing_id integer,
    primtarget bigint,
    sectarget bigint,
    spectrographid smallint,
    sourcetype character varying(128),
    targettype character varying(128),
    ra double precision,
    "dec" double precision,
    cx double precision,
    cy double precision,
    cz double precision,
    xfocal real,
    yfocal real,
    lambdaeff real,
    bluefiber integer,
    zoffset real,
    z real,
    zerr real,
    zwarning integer,
    class character varying(32),
    subclass character varying(32),
    rchi2 real,
    dof real,
    rchi2diff real,
    z_noqso real,
    zerr_noqso real,
    zwarning_noqso integer,
    class_noqso character varying(32),
    subclass_noqso character varying(32),
    rchi2diff_noqso real,
    z_person real,
    class_person character varying(32),
    comments_person character varying(200),
    tfile character varying(32),
    tcolumn_0 smallint,
    tcolumn_1 smallint,
    tcolumn_2 smallint,
    tcolumn_3 smallint,
    tcolumn_4 smallint,
    tcolumn_5 smallint,
    tcolumn_6 smallint,
    tcolumn_7 smallint,
    tcolumn_8 smallint,
    tcolumn_9 smallint,
    npoly real,
    theta_0 real,
    theta_1 real,
    theta_2 real,
    theta_3 real,
    theta_4 real,
    theta_5 real,
    theta_6 real,
    theta_7 real,
    theta_8 real,
    theta_9 real,
    veldisp real,
    veldisperr real,
    veldispz real,
    veldispzerr real,
    veldispchi2 real,
    veldispnpix integer,
    veldispdof integer,
    wavemin real,
    wavemax real,
    wcoverage real,
    snmedian_u real,
    snmedian_g real,
    snmedian_r real,
    snmedian_i real,
    snmedian_z real,
    snmedian real,
    chi68p real,
    fracnsigma_1 real,
    fracnsigma_2 real,
    fracnsigma_3 real,
    fracnsigma_4 real,
    fracnsigma_5 real,
    fracnsigma_6 real,
    fracnsigma_7 real,
    fracnsigma_8 real,
    fracnsigma_9 real,
    fracnsigma_10 real,
    fracnsighi_1 real,
    fracnsighi_2 real,
    fracnsighi_3 real,
    fracnsighi_4 real,
    fracnsighi_5 real,
    fracnsighi_6 real,
    fracnsighi_7 real,
    fracnsighi_8 real,
    fracnsighi_9 real,
    fracnsighi_10 real,
    fracnsiglo_1 real,
    fracnsiglo_2 real,
    fracnsiglo_3 real,
    fracnsiglo_4 real,
    fracnsiglo_5 real,
    fracnsiglo_6 real,
    fracnsiglo_7 real,
    fracnsiglo_8 real,
    fracnsiglo_9 real,
    fracnsiglo_10 real,
    spectroflux_u real,
    spectroflux_g real,
    spectroflux_r real,
    spectroflux_i real,
    spectroflux_z real,
    spectrosynflux_u real,
    spectrosynflux_g real,
    spectrosynflux_r real,
    spectrosynflux_i real,
    spectrosynflux_z real,
    spectrofluxivar_u real,
    spectrofluxivar_g real,
    spectrofluxivar_r real,
    spectrofluxivar_i real,
    spectrofluxivar_z real,
    spectrosynfluxivar_u real,
    spectrosynfluxivar_g real,
    spectrosynfluxivar_r real,
    spectrosynfluxivar_i real,
    spectrosynfluxivar_z real,
    spectroskyflux_u real,
    spectroskyflux_g real,
    spectroskyflux_r real,
    spectroskyflux_i real,
    spectroskyflux_z real,
    anyandmask integer,
    anyormask integer,
    platesn2 real,
    deredsn2 real,
    snturnoff real,
    sn1_g real,
    sn1_r real,
    sn1_i real,
    sn2_g real,
    sn2_r real,
    sn2_i real,
    elodiefilename character varying(32),
    elodieobject character varying(32),
    elodiesptype character varying(32),
    elodiebv real,
    elodieteff real,
    elodielogg real,
    elodiefeh real,
    elodiez real,
    elodiezerr real,
    elodiezmodelerr real,
    elodierchi2 real,
    elodiedof real,
    htmid bigint,
    loadversion integer
);
