CREATE TABLE catalogdb.sdss_dr17_specobj (
    survey character varying,
    instrument character varying,
    chunk character varying,
    programname character varying,
    platerun character varying,
    platequality character varying,
    platesn2 real,
    deredsn2 real,
    lambda_eff real,
    bluefiber integer,
    zoffset real,
    snturnoff real,
    nturnoff integer,
    specprimary smallint,
    specsdss smallint,
    speclegacy smallint,
    specsegue smallint,
    specsegue1 smallint,
    specsegue2 smallint,
    specboss smallint,
    boss_specobj_id integer,
    specobjid character varying NOT NULL,
    fluxobjid character varying,
    bestobjid character varying,
    targetobjid character varying,
    plateid character varying,
    nspecobs smallint,
    firstrelease character varying,
    run2d character varying,
    run1d character varying,
    designid integer,
    cx double precision,
    cy double precision,
    cz double precision,
    xfocal real,
    yfocal real,
    sourcetype character varying,
    targettype character varying,
    thing_id_targeting bigint,
    thing_id integer,
    primtarget integer,
    sectarget integer,
    legacy_target1 integer,
    legacy_target2 integer,
    special_target1 bigint,
    special_target2 bigint,
    segue1_target1 integer,
    segue1_target2 integer,
    segue2_target1 integer,
    segue2_target2 integer,
    marvels_target1 integer,
    marvels_target2 integer,
    boss_target1 bigint,
    boss_target2 bigint,
    eboss_target0 bigint,
    eboss_target1 bigint,
    eboss_target2 bigint,
    eboss_target_id bigint,
    ancillary_target1 bigint,
    ancillary_target2 bigint,
    spectrographid smallint,
    plate integer,
    tile integer,
    mjd integer,
    fiberid integer,
    objid text,
    plug_ra double precision,
    plug_dec double precision,
    class character varying,
    subclass character varying,
    z real,
    z_err real,
    rchi2 real,
    dof integer,
    rchi2diff real,
    tfile character varying,
    tcolumn text,
    npoly integer,
    theta text,
    vdisp real,
    vdisp_err real,
    vdispz real,
    vdispz_err real,
    vdispchi2 real,
    vdispnpix real,
    vdispdof integer,
    wavemin real,
    wavemax real,
    wcoverage real,
    zwarning integer,
    sn_median_all real,
    sn_median text,
    chi68p real,
    fracnsigma text,
    fracnsighi text,
    fracnsiglo text,
    spectroflux text,
    spectroflux_ivar text,
    spectrosynflux text,
    spectrosynflux_ivar text,
    spectroskyflux text,
    anyandmask integer,
    anyormask integer,
    spec1_g real,
    spec1_r real,
    spec1_i real,
    spec2_g real,
    spec2_r real,
    spec2_i real,
    elodie_filename character varying,
    elodie_object character varying,
    elodie_sptype character varying,
    elodie_bv real,
    elodie_teff real,
    elodie_logg real,
    elodie_feh real,
    elodie_z real,
    elodie_z_err real,
    elodie_z_modelerr real,
    elodie_rchi2 real,
    elodie_dof integer,
    z_noqso real,
    z_err_noqso real,
    zwarning_noqso integer,
    class_noqso character varying,
    subclass_noqso character varying,
    rchi2diff_noqso real,
    z_person real,
    class_person integer,
    z_conf_person integer,
    comments_person character varying,
    calibflux text,
    calibflux_ivar text,
    bestobjid_bigint bigint,
    fluxobjid_bigint bigint
);
