CREATE TABLE catalogdb.twoqz_sixqz (
    name character(16),
    ra_j2000 character(11),
    dec_j2000 character(11),
    catalogue_number bigint,
    catalogue_name character(10),
    sector character(25),
    ra_b1950 character(11),
    dec_b1950 character(11),
    ukst_field integer,
    xapm real,
    yapm real,
    ra_rad double precision,
    dec_rad double precision,
    bj real,
    u_bj real,
    bj_r real,
    nobs integer,
    z1 real,
    q1 integer,
    id1 character(10),
    date1 character(8),
    fld1 integer,
    fibre1 integer,
    s_n1 real,
    z2 real,
    q2 integer,
    id2 character(10),
    date2 character(8),
    fld2 integer,
    fibre2 integer,
    s_n2 real,
    zprev real,
    radio real,
    x_ray real,
    dust real,
    comments1 character(20),
    comments2 character(20),
    ra_degree double precision,
    dec_degree double precision,
    pkey bigint NOT NULL
);
