CREATE TABLE catalogdb.tycho2 (
    tyc1 integer,
    tyc2 integer,
    tyc3 integer,
    pflag character varying(1),
    ramdeg double precision,
    demdeg double precision,
    pmra double precision,
    pmde double precision,
    e_ramdeg integer,
    e_demdeg integer,
    e_pmra double precision,
    e_pmde double precision,
    epram double precision,
    epdem double precision,
    num integer,
    q_ramdeg double precision,
    q_demdeg double precision,
    q_pmra double precision,
    q_pmde double precision,
    btmag real,
    e_btmag real,
    vtmag real,
    e_vtmag real,
    prox integer,
    tyc character varying(1),
    hip bigint,
    ccdm character varying(3),
    radeg double precision,
    dedeg double precision,
    epra_1990 double precision,
    epde_1990 double precision,
    e_radeg double precision,
    e_dedeg double precision,
    posflg character varying(1),
    corr real,
    flag character varying(1),
    mflag character varying(1),
    designation text NOT NULL,
    tycid integer NOT NULL,
    designation2 text
);
