CREATE TABLE catalogdb.uvotssc1 (
    name character varying(17),
    oseq bigint,
    obsid bigint,
    nf bigint,
    srcid bigint,
    radeg double precision,
    dedeg double precision,
    e_radeg double precision,
    e_dedeg double precision,
    ruvw2 real,
    ruvm2 real,
    ruvw1 real,
    ru real,
    rb real,
    rv real,
    nd bigint,
    suvw2 real,
    suvm2 real,
    suvw1 real,
    su real,
    sb real,
    sv real,
    uvw2 double precision,
    uvm2 double precision,
    uvw1 double precision,
    umag double precision,
    bmag double precision,
    vmag double precision,
    uvw2_ab double precision,
    uvm2_ab double precision,
    uvw1_ab double precision,
    u_ab double precision,
    b_ab double precision,
    v_ab double precision,
    e_uvw2 double precision,
    e_uvm2 double precision,
    e_uvw1 double precision,
    e_umag double precision,
    e_bmag double precision,
    e_vmag double precision,
    f_uvw2 double precision,
    f_uvm2 double precision,
    f_uvw1 double precision,
    f_u double precision,
    f_b double precision,
    f_v double precision,
    e_f_uvw2 double precision,
    e_f_uvm2 double precision,
    e_f_uvw1 double precision,
    e_f_u double precision,
    e_f_b double precision,
    e_f_v double precision,
    auvw2 double precision,
    auvm2 double precision,
    auvw1 double precision,
    au double precision,
    ab double precision,
    av double precision,
    buvw2 double precision,
    buvm2 double precision,
    buvw1 double precision,
    bu double precision,
    bb double precision,
    bv double precision,
    pauvw2 real,
    pauvm2 real,
    pauvw1 real,
    pau real,
    pab real,
    pav real,
    xuvw2 integer,
    xuvm2 integer,
    xuvw1 integer,
    xu integer,
    xb integer,
    xv integer,
    fuvw2 integer,
    fuvm2 integer,
    fuvw1 integer,
    fu integer,
    fb integer,
    fv integer,
    id bigint NOT NULL
);
